version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ".env"
    ports:
      - "5433:5432"
    networks:
      - dbt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dbt -U testuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  # dbt:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ".env"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - dbt_network

networks:
  dbt_network:
