[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sdk"
version = "0.0.2"
requires-python = ">=3.11"
dependencies = [
"boto3==1.28.2",
"pydantic==2.1.1",
"pandas==2.0.3",
"pyarrow==12.0.1",
]
